# Generated by Django 4.0.3 on 2023-05-10 07:36

import Bus.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'List of Books',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=30)),
                ('bus_number', models.CharField(max_length=10, unique=True)),
                ('nos', models.DecimalField(decimal_places=0, max_digits=2)),
                ('rem', models.DecimalField(decimal_places=0, max_digits=2)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'List of Buses',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('card_holder_name', models.CharField(max_length=50)),
                ('card_number', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('addr1', models.CharField(max_length=400)),
                ('addr2', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Kerala', 'Kerala'), ('Gujrat', 'Gujrat'), ('Mumbai', 'Mumbai'), ('Karnataka', 'Karnataka')], max_length=50)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Register_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.IntegerField()),
                ('profile_pic', models.ImageField(blank=True, default='profile_pic/default.png', null=True, upload_to='profile_pic')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(blank=True, default='Male', max_length=200, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('added_on', models.DateField(auto_now_add=True, null=True)),
                ('uploaded_on', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='Bus.book')),
            ],
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('dest', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[Bus.models.validate_price_not_zero])),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.bus')),
            ],
            options={
                'verbose_name_plural': 'Bus Routes',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.bus'),
        ),
    ]
